### ISSUE TITLE
Prometheus error ingesting samples too old using electricity maps

### ISSUE THREAD

**Issue by Lennart01** [thegreenwebfoundation/grid-intensity-go#86]
Prometheus does not allow metrics to be too far behind the current timestamp. The unestimated value may be way out of sync and cannot be ingested with a standard Prometheus configuration.
In this example, the unestimated value is 6hs out of sync. 
I honestly do not know what the best course of action is here.
The exporter is therefore currently unusable with Prometheus and electricity maps.

```
grid_intensity_carbon_average{is_estimated="false",location="DE",node="scrumlr-prod-nodes-1-ec030b36",provider="ElectricityMaps",region="",units="gCO2e per kWh"} 216 1724310000000
grid_intensity_carbon_average{is_estimated="true",location="DE",node="scrumlr-prod-nodes-1-ec030b36",provider="ElectricityMaps",region="",units="gCO2e per kWh"} 142 1724324400000
```

```
ts=2024-08-22T11:50:54.197Z caller=scrape.go:1747 level=warn component="scrape manager" scrape_pool=serviceMonitor/prometheus/grid-intensity-exporter/0 target=http://10.0.2.142:8000/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=1
```

**Comment by locomundo** [comment]
Hi Lennart,

To avoid this problem you need to configure the property `outOfOrderTimeWindow` to extend the time window. We are using ElectricityMaps in Germany and a value of `3h` seems enough. We have it running for a couple months now.

I will make a PR adding this to the documentation, since we found out after [this](https://github.com/thegreenwebfoundation/grid-intensity-go/pull/83) PR was merged.

This should solve the problem for you too, let me know.

**Comment by Lennart01** [comment]
Hey, yeah that works awesome, thanks a lot.
I tinkered with it yesterday but set the value too low.
Documenting this would be awesome 👍.
I am going to close this issue, works as intended.
